package com.movingmaker.commentdiary.presentation.util

const val KAKAO = "KAKAO"
const val EMAIL = "EMAIL"

const val TERMS_URL =
    "https://glittery-silk-987.notion.site/fb0c6c765a7a411c9362dc8d102c95e0"
const val POLICY_URL = "https://www.notion.so/59a704f6702f4382b9398fa3b4a0d780"

enum class FRAGMENT_NAME {
    //main
    MY_PAGE, MY_ACCOUNT, SIGN_OUT, TERMS, SENDED_COMMENT_LIST, CHANGE_PASSWORD,
    PUSHALARM_ONOFF, RECEIVED_DIARY, CALENDAR_WITH_DIARY, GATHER_DIARY, WRITE_DIARY, COMMENT_DIARY_DETAIL, ALONE_DIARY_DETAIL,

    //onboarding
    LOGIN, LOGIN_BEFORE, FIND_PASSWORD, SIGNUP_PASSWORD, SIGNUP_CODE, SIGNUP_EMAIL, SIGNUP_SUCCESS, SIGNUP_TERMS, KAKAO_TERMS
}

enum class DIARY_TYPE {
    ALONE_DIARY, COMMENT_DIARY
}
